//
//  YoudaoTranslate.m
//  Bob
//
//  Created by ripper on 2019/12/12.
//  Copyright © 2019 ripperhe. All rights reserved.
//

#import "YoudaoTranslate.h"

MMOrderedDictionary * YoudaoSupportLanguageDict() {
    static MMOrderedDictionary *_langDict = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _langDict = [[MMOrderedDictionary alloc] initWithKeysAndObjects:
                     @(Language_auto), @"auto",
                     @(Language_zh_Hans), @"zh-CHS",
                     @(Language_yue), @"yue",
                     @(Language_en), @"en",
                     @(Language_ja), @"ja",
                     @(Language_ko), @"ko",
                     @(Language_fr), @"fr",
                     @(Language_es), @"es",
                     @(Language_pt), @"pt",
                     @(Language_it), @"it",
                     @(Language_ru), @"ru",
                     @(Language_vi), @"vi",
                     @(Language_de), @"de",
                     @(Language_ar), @"ar",
                     @(Language_id), @"id",
                     @(Language_af), @"af",
                     @(Language_bs), @"bs",
                     @(Language_bg), @"bg",
                     @(Language_ca), @"ca",
                     @(Language_hr), @"hr",
                     @(Language_cs), @"cs",
                     @(Language_da), @"da",
                     @(Language_nl), @"nl",
                     @(Language_et), @"et",
                     @(Language_fj), @"fj",
                     @(Language_fi), @"fi",
                     @(Language_el), @"el",
                     @(Language_ht), @"ht",
                     @(Language_he), @"he",
                     @(Language_hi), @"hi",
                     @(Language_mww), @"mww",
                     @(Language_hu), @"hu",
                     @(Language_sw), @"sw",
                     @(Language_tlh), @"tlh",
                     @(Language_lv), @"lv",
                     @(Language_lt), @"lt",
                     @(Language_ms), @"ms",
                     @(Language_mt), @"mt",
                     @(Language_no), @"no",
                     @(Language_fa), @"fa",
                     @(Language_pl), @"pl",
                     @(Language_otq), @"otq",
                     @(Language_ro), @"ro",
                     @(Language_sr_Cyrl), @"sr-Cyrl",
                     @(Language_sr_Latn), @"sr-Latn",
                     @(Language_sk), @"sk",
                     @(Language_sv), @"sv",
                     @(Language_ty), @"ty",
                     @(Language_th), @"th",
                     @(Language_to), @"to",
                     @(Language_tr), @"tr",
                     @(Language_uk), @"uk",
                     @(Language_ur), @"ur",
                     @(Language_cy), @"cy",
                     @(Language_yua), @"yua",
                     @(Language_sq), @"sq",
                     @(Language_am), @"am",
                     @(Language_hy), @"hy",
                     @(Language_az), @"az",
                     @(Language_bn), @"bn",
                     @(Language_eu), @"eu",
                     @(Language_be), @"be",
                     @(Language_ceb), @"ceb",
                     @(Language_co), @"co",
                     @(Language_eo), @"eo",
                     @(Language_tl), @"tl",
                     @(Language_fy), @"fy",
                     @(Language_gl), @"gl",
                     @(Language_ka), @"ka",
                     @(Language_gu), @"gu",
                     @(Language_ha), @"ha",
                     @(Language_haw), @"haw",
                     @(Language_is), @"is",
                     @(Language_ig), @"ig",
                     @(Language_ga), @"ga",
                     @(Language_jw), @"jw",
                     @(Language_kn), @"kn",
                     @(Language_kk), @"kk",
                     @(Language_km), @"km",
                     @(Language_ku), @"ku",
                     @(Language_ky), @"ky",
                     @(Language_lo), @"lo",
                     @(Language_la), @"la",
                     @(Language_lb), @"lb",
                     @(Language_mk), @"mk",
                     @(Language_mg), @"mg",
                     @(Language_mi), @"mi",
                     @(Language_ml), @"ml",
                     @(Language_mr), @"mr",
                     @(Language_mn), @"mn",
                     @(Language_my), @"my",
                     @(Language_ne), @"ne",
                     @(Language_ny), @"ny",
                     @(Language_ps), @"ps",
                     @(Language_pa), @"pa",
                     @(Language_sm), @"sm",
                     @(Language_gd), @"gd",
                     @(Language_st), @"st",
                     @(Language_sn), @"sn",
                     @(Language_sd), @"sd",
                     @(Language_si), @"si",
                     @(Language_so), @"so",
                     @(Language_su), @"su",
                     @(Language_tg), @"tg",
                     @(Language_ta), @"ta",
                     @(Language_te), @"te",
                     @(Language_uz), @"uz",
                     @(Language_xh), @"xh",
                     @(Language_yi), @"yi",
                     @(Language_yo), @"yo",
                     @(Language_zu), @"zu",
                     nil];
    });
    return _langDict;
}

@implementation YoudaoTranslate

@end
